remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
logo: /Icon.png
navigation:
  - title: Terms of Service
    url: /tos-en
  - title: Privacy Policy
    url: /pp-en
